---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/raks-tt/infra-deployments.git
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-kepler-dashboard
