apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../base/external-secrets
- https://github.com/konflux-ci/integration-service/config/default?ref=01dd602af0cd97c0d4d53d6b1b9e8785673cf100
- https://github.com/konflux-ci/integration-service/config/snapshotgc?ref=01dd602af0cd97c0d4d53d6b1b9e8785673cf100

images:
- name: quay.io/redhat-appstudio/integration-service
  newName: quay.io/redhat-appstudio/integration-service
  newTag: 01dd602af0cd97c0d4d53d6b1b9e8785673cf100

configMapGenerator:
- name: integration-config
  literals:
    - CONSOLE_NAME="Red Hat Konflux"
    - CONSOLE_URL="https://console.redhat.com/preview/application-pipeline/ns/{{ .Namespace }}/pipelinerun/{{ .PipelineRunName }}"
    - CONSOLE_URL_TASKLOG="https://console.redhat.com/preview/application-pipeline/ns/{{ .Namespace }}/pipelinerun/{{ .PipelineRunName }}/logs/{{ .TaskName }}"
- name: pipelinerun-options
  literals:
    - PIPELINE_TIMEOUT="3h"
    - TASKS_TIMEOUT="2h"
    - FINALLY_TIMEOUT="1h"

namespace: integration-service

patches:
  - path: pipelines-as-code-secret.yaml
    target:
      name: pipelines-as-code-secret
      kind: ExternalSecret
      group: external-secrets.io
      version: v1beta1
  - path: manager_resources_patch.yaml
