apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: power-monitoring
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: power-monitoring-{{nameNormalized}}
    spec:
      project: default
      source:
        path: components/power-monitoring
        repoURL: https://github.com/redhat-appstudio/infra-deployments.git
        targetRevision: main
      destination:
        namespace: power-monitoring
        server: '{{server}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 50
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
