apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ibm-s390x-static-ssh-key
  namespace: multi-platform-controller
  labels:
    build.appstudio.redhat.com/multi-platform-secret: "true"
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
spec:
  dataFrom:
    - extract:
        key: production/build/multi-platform-controller/stone-prod-p02-ibm-s390x-static-ssh-key
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-stonesoup-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: ibm-s390x-static-ssh-key

